version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    container_name: landing_page_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html          # Mapea los archivos de tu proyecto
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mapea tu configuración de Nginx
    restart: always