version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    container_name: landing_page_nginx
    ports:
      - "80:80" # O "- "9027:80"" si necesitas el puerto 9027 en el host
    volumes:
      # Mapea la carpeta raíz de tu repositorio (index.html, style.css, assets)
      - ./:/usr/share/nginx/html          
      
      # Monta tu archivo de configuración en el subdirectorio conf.d de Nginx.
      # ¡ESTA ES LA CLAVE PARA SOLUCIONAR EL ERROR!
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
    restart: always