version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    container_name: landing_page_nginx_default
    ports:
      - "9027:80" # Mapea el puerto 80 del host al puerto 80 del contenedor
      # Si necesitas acceder desde el puerto 9027, cámbialo a "- "9027:80""
    volumes:
      # Monta la carpeta actual de tu repositorio (donde está index.html, style.css y assets)
      # en el directorio donde Nginx espera los archivos web.
      - ./:/usr/share/nginx/html
    restart: always