version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    container_name: landing_page_nginx
    ports:
      - "9027:80" # Mapea el puerto 80 del host al puerto 80 del contenedor
      # Si necesitas el puerto 9027 en el host, cámbialo a "- "9027:80""
    volumes:
      # Mapea la carpeta raíz de tu repositorio (donde están index.html, style.css y assets)
      # al directorio de Nginx dentro del contenedor.
      - ./:/usr/share/nginx/html          
      
      # Mapea tu archivo nginx.conf personalizado al lugar donde Nginx lo espera.
      # ":ro" significa "read-only" (solo lectura), buena práctica para archivos de configuración.
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
    restart: always